extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/no-explicit-any": off
env:
  browser: true
